version: '3.8'

services:
  # Neo4j Database (Production Optimized)
  neo4j:
    image: neo4j:latest
    container_name: neo4j-rag
    restart: unless-stopped
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    environment:
      # Authentication
      - NEO4J_AUTH=neo4j/password

      # Memory Configuration (Production Optimized)
      - NEO4J_server_memory_heap_initial__size=2G
      - NEO4J_server_memory_heap_max__size=4G
      - NEO4J_server_memory_pagecache_size=2G

      # Security Settings
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*

    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '4.0'
        reservations:
          memory: 4G
          cpus: '2.0'

    networks:
      - neo4j-network

  # Ultra-Efficient BitNet RAG Application (87% memory reduction)
  bitnet-rag:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitnet-rag-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Neo4j Connection
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password

      # Azure OpenAI Configuration (for embeddings)
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}

      # BitNet Configuration (optional - can use fallback)
      - BITNET_ENDPOINT=${BITNET_ENDPOINT:-}
      - BITNET_API_KEY=${BITNET_API_KEY:-}

      # BitNet Mode
      - BITNET_MODE=enabled

    depends_on:
      - neo4j

    # Ultra-low resource requirements (BitNet efficiency)
    deploy:
      resources:
        limits:
          memory: 512M   # 87% reduction from 4GB
          cpus: '0.5'    # Minimal CPU usage
        reservations:
          memory: 256M
          cpus: '0.25'

    networks:
      - neo4j-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  neo4j-network:
    driver: bridge

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
